# baseURL = "https://www.netket.org"
languageCode = "en-us"
title = "NetKet"
copyright = "Copyright 2019-2022, The Netket authors - All rights reserved."

[author]
  name = "Filippo Vicentini and Giuseppe Carleo"

[params]
description = "The Machine Learning Toolbox for Quantum Physics"
slack_link = "https://join.slack.com/t/mlquantum/shared_invite/zt-19wibmfdv-LLRI6i43wrLev6oQX0OfOw"

[params.image]
  url = "logo/logo_transparent_small.png"
  width = 800
  height = 600


[params.navbar]
logo = "logo/logonav.png"
linksOnlyIcon = true

[params.navbar.button]
url = "https://netket.readthedocs.io"
text = "Get Started"

[markup.goldmark.renderer]
unsafe = true

[[params.keyfeatures.features]]
title = "Neural Quantum States"
text = "NetKet provides state-of-the-art Neural-Network Quantum states, and advanced learning algorithms to study many-body quantum systems."

[[params.keyfeatures.features]]
title = "Jax-powered"
text = "Netket is based on Jax, therefore you can run on CPUs, GPUs and TPUs, using Sharding or MPI to distribute among multiple nodes."

[[params.keyfeatures.features]]
title = "Interoperable"
text = "NetKet can easily interoperate with other tools such as [OpenFermion](https://quantumai.google/openfermion) or [QuTiP](https://qutip.org/)."

[[params.keyfeatures.features]]
title = "Multi-framework"
text = "NetKet's built in models are implemented using [Flax](https://flax.readthedocs.io/), but it is also compatible with [Equinox](https://docs.kidger.site/equinox/), [Haiku](https://github.com/deepmind/dm-haiku) and can be made compatible with future frameworks."

[[params.keyfeatures.features]]
title = "Easy to use"
text = "NetKet has an high-level syntax that is easy to use, while exposing low level objects that can be combined together to develop novel algorithms."

[[params.keyfeatures.features]]
title = "Open source"
text = "NetKet is a collaborative effort by a group of researchers. We are constantly looking for new contributors. Do get in touch with us through the [Github Discussions](https://github.com/netket/netket/discussions) or through our Slack Channel"

[params.installationWidget]
title = "INSTALLATION WIDGET"

  [[params.installationWidget.features]]
  title = "Quality 1"
  text = "Text on Quality 1"

